/*
 * This jQuery calculator app uses eventlisteners (attached to the appropriate HTML elements) to perform
 * arithmetic operations on two numbers (generated by the user clicking on the buttons). Future versions
 * will utilize more advanced operations and have more number memory to perform repeated operations more easily.
 * Future versions will also support typing numbers, rather than just clicking buttons.
 */

"use strict";

//number objects to be constructed/modified by button clicks
 var no1Obj = {
   numStr : '',
   currentNum : true
 }

 var no2Obj = {
   numStr : '',
   currentNum : false
 }

//object storing the name of the most recetly clicked operator button
var currentOp = {
  name : ''
}

//operator functions:
 function plus(num1, num2){ // function to be used as a callback for the "+" button's event listener
   var float1 = Number(num1.numStr);
   var float2 = Number(num2.numStr);
   var thisOp = float1 + float2;
   return thisOp;
 }
 function minus(num1, num2){ // function to be used as a callback for the "-" button's event listener
   var float1 = Number(num1.numStr);
   var float2 = Number(num2.numStr);
   var thisOp = float1 - float2;
   return thisOp;
 }
 function times(num1, num2){ // function to be used as a callback for the "*" button's event listener
   var float1 = Number(num1.numStr);
   var float2 = Number(num2.numStr);
   var thisOp = float1 * float2;
   return thisOp;
 }
 function divide(num1, num2){ // function to be used as a callback for the "/" button's event listener
   var float1 = Number(num1.numStr);
   var float2 = Number(num2.numStr);
   var thisOp = float1 / float2;
   return thisOp;
 }

$(document).ready(function(){
  //number building: create a number to be used as a operand by concatinating digits in a string
  $('.number').click(function(){
    var currentClick = ($(this).val());
    if (no1Obj.currentNum) {
      no1Obj.numStr = no1Obj.numStr.concat(currentClick);
      $('#display').val(no1Obj.numStr);
      $('#output').html(no1Obj.numStr + ' ___no 1 current');
    }else{
      no2Obj.numStr = no2Obj.numStr.concat(currentClick);
      $('#display').val(no2Obj.numStr);
      $('#output').html(no2Obj.numStr + ' ___no 2 current');
    }
  });

  $('.operator').click(function(){
    if (no1Obj.currentNum){
      no1Obj.currentNum = false;
      no2Obj.currentNum = true;
    }


    $('#output').html('current number changed');//works up to here with switching currentNum
    currentOp.name = ($(this).attr('id'));///// works up to here with changing currentOp
    $('#output').html(currentOp.name);
  });

  $('#clearButton').click(function(){
    no1Obj.numStr = '';
    no1Obj.currentNum = true;
    no2Obj.numStr = '';
    no2Obj.currentNum = false;
    currentOp.name = '';
    $('#display').val('');
    $('#output').html('');
  });//clear button works

  $('#equalsButton').click(function(){
    if (no2Obj.numStr == ''){
      return;
    }
    var result;
    if (currentOp.name == ''){
      $('#display').val(no1Obj.numStr);
      $('#output').html(no1Obj.numStr);
    }else if (currentOp.name == "addButton"){
      result = plus(no1Obj, no2Obj);
    }else if (currentOp.name == "subtractButton"){
      result = minus(no1Obj, no2Obj);
    }else if (currentOp.name == "multiplyButton"){
      result = times(no1Obj, no2Obj);
    }else if (currentOp.name == "divideButton"){
      result = divide(no1Obj, no2Obj);
    }

    $('#output').html(result);
    $('#display').val(result);
    no1Obj.numStr = result;
    no1Obj.currentNum = false;
    no2Obj.numStr = '';
    no2Obj.currentNum = true;
    //currentOp.name = '';

  });


  // $('#output').html(); 

});
